services:
  - type: web
    name: police-records-python-service
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: "5001"
    healthCheckPath: /health
